[COREGEN.VHDL Component Instantiation.reg64]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component reg64"
text005="    port ("
text006="    D: IN std_logic_VECTOR(63 downto 0);"
text007="    Q: OUT std_logic_VECTOR(63 downto 0);"
text008="    G: IN std_logic;"
text009="    GE: IN std_logic);"
text010="end component;"
text011=""
text012=""
text013=""
text014=""
text015=" "
text016="-------------------------------------------------------------"
text017=" "
text018="-- The following code must appear in the VHDL architecture body."
text019="-- Substitute your own instance name and net names."
text020=" "
text021="your_instance_name : reg64"
text022="        port map ("
text023="            D => D,"
text024="            Q => Q,"
text025="            G => G,"
text026="            GE => GE);"
text027=" "
[COREGEN.VERILOG Component Instantiation.reg64]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="reg64 YourInstanceName ("
text007="    .D(D),"
text008="    .Q(Q),"
text009="    .G(G),"
text010="    .GE(GE));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.count32]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component count32"
text005="    port ("
text006="    Q: OUT std_logic_VECTOR(31 downto 0);"
text007="    CLK: IN std_logic;"
text008="    LOAD: IN std_logic;"
text009="    L: IN std_logic_VECTOR(31 downto 0);"
text010="    SSET: IN std_logic);"
text011="end component;"
text012=""
text013=""
text014=""
text015=""
text016=" "
text017="-------------------------------------------------------------"
text018=" "
text019="-- The following code must appear in the VHDL architecture body."
text020="-- Substitute your own instance name and net names."
text021=" "
text022="your_instance_name : count32"
text023="        port map ("
text024="            Q => Q,"
text025="            CLK => CLK,"
text026="            LOAD => LOAD,"
text027="            L => L,"
text028="            SSET => SSET);"
text029=" "
[COREGEN.VERILOG Component Instantiation.count32]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="count32 YourInstanceName ("
text007="    .Q(Q),"
text008="    .CLK(CLK),"
text009="    .LOAD(LOAD),"
text010="    .L(L),"
text011="    .SSET(SSET));"
text012=""
text013=" "
[COREGEN.VHDL Component Instantiation.count64]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component count64"
text005="    port ("
text006="    Q: OUT std_logic_VECTOR(63 downto 0);"
text007="    CLK: IN std_logic;"
text008="    LOAD: IN std_logic;"
text009="    L: IN std_logic_VECTOR(63 downto 0);"
text010="    CE: IN std_logic);"
text011="end component;"
text012=""
text013=""
text014=""
text015=""
text016=" "
text017="-------------------------------------------------------------"
text018=" "
text019="-- The following code must appear in the VHDL architecture body."
text020="-- Substitute your own instance name and net names."
text021=" "
text022="your_instance_name : count64"
text023="        port map ("
text024="            Q => Q,"
text025="            CLK => CLK,"
text026="            LOAD => LOAD,"
text027="            L => L,"
text028="            CE => CE);"
text029=" "
[COREGEN.VERILOG Component Instantiation.count64]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="count64 YourInstanceName ("
text007="    .Q(Q),"
text008="    .CLK(CLK),"
text009="    .LOAD(LOAD),"
text010="    .L(L),"
text011="    .CE(CE));"
text012=""
text013=" "
[COREGEN.VHDL Component Instantiation.keyfifo]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component keyfifo"
text005="    port ("
text006="    clk: IN std_logic;"
text007="    sinit: IN std_logic;"
text008="    din: IN std_logic_VECTOR(63 downto 0);"
text009="    wr_en: IN std_logic;"
text010="    rd_en: IN std_logic;"
text011="    dout: OUT std_logic_VECTOR(63 downto 0);"
text012="    full: OUT std_logic;"
text013="    empty: OUT std_logic);"
text014="end component;"
text015=""
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : keyfifo"
text026="        port map ("
text027="            clk => clk,"
text028="            sinit => sinit,"
text029="            din => din,"
text030="            wr_en => wr_en,"
text031="            rd_en => rd_en,"
text032="            dout => dout,"
text033="            full => full,"
text034="            empty => empty);"
text035=" "
[COREGEN.VERILOG Component Instantiation.keyfifo]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="keyfifo YourInstanceName ("
text007="    .clk(clk),"
text008="    .sinit(sinit),"
text009="    .din(din),"
text010="    .wr_en(wr_en),"
text011="    .rd_en(rd_en),"
text012="    .dout(dout),"
text013="    .full(full),"
text014="    .empty(empty));"
text015=""
text016=" "
[COREGEN.VHDL Component Instantiation.reg5_core_impl]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component reg5_core_impl"
text005="    port ("
text006="    D: IN std_logic_VECTOR(4 downto 0);"
text007="    Q: OUT std_logic_VECTOR(4 downto 0);"
text008="    CLK: IN std_logic;"
text009="    CE: IN std_logic;"
text010="    SCLR: IN std_logic);"
text011="end component;"
text012=""
text013=""
text014=""
text015=""
text016=" "
text017="-------------------------------------------------------------"
text018=" "
text019="-- The following code must appear in the VHDL architecture body."
text020="-- Substitute your own instance name and net names."
text021=" "
text022="your_instance_name : reg5_core_impl"
text023="        port map ("
text024="            D => D,"
text025="            Q => Q,"
text026="            CLK => CLK,"
text027="            CE => CE,"
text028="            SCLR => SCLR);"
text029=" "
[COREGEN.VERILOG Component Instantiation.reg5_core_impl]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="reg5_core_impl YourInstanceName ("
text007="    .D(D),"
text008="    .Q(Q),"
text009="    .CLK(CLK),"
text010="    .CE(CE),"
text011="    .SCLR(SCLR));"
text012=""
text013=" "
[COREGEN.VHDL Component Instantiation.rc5_reg32]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component rc5_reg32"
text005="    port ("
text006="    D: IN std_logic_VECTOR(31 downto 0);"
text007="    Q: OUT std_logic_VECTOR(31 downto 0);"
text008="    CLK: IN std_logic;"
text009="    CE: IN std_logic;"
text010="    SCLR: IN std_logic;"
text011="    SSET: IN std_logic);"
text012="end component;"
text013=""
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : rc5_reg32"
text024="        port map ("
text025="            D => D,"
text026="            Q => Q,"
text027="            CLK => CLK,"
text028="            CE => CE,"
text029="            SCLR => SCLR,"
text030="            SSET => SSET);"
text031=" "
[COREGEN.VERILOG Component Instantiation.rc5_reg32]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="rc5_reg32 YourInstanceName ("
text007="    .D(D),"
text008="    .Q(Q),"
text009="    .CLK(CLK),"
text010="    .CE(CE),"
text011="    .SCLR(SCLR),"
text012="    .SSET(SSET));"
text013=""
text014=" "
