-- ProjNav VHDL simulation template: core_key_latch_tb.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
