-- ProjNav VHDL simulation template: keygen_rc5_72_tbw.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
