-- ProjNav VHDL simulation template: compare_statistical_fast_tb.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
